- docs/cmdlets-reference/get-cohesityprotectionjobstatus.md
- docs/cmdlets-reference/recover-cohesitybackuptoview.md
- docs/cmdlets-reference/set-cohesityalertresolutions.md
- docs/cmdlets-reference/update-cohesityprotectionjobrun.md
Update-CohesityProtectionJobRun, Set-CohesityAlertResolutions, Recover-CohesityBackupToView, Get-CohesityProtectionJobStatus
> Documentation for script based commandlets

- src/Cohesity.Powershell.Models/AlertingConfig.cs
- src/Cohesity.Powershell/Cohesity.PowerShell.Core.psd1
- src/Cohesity.Powershell/Cohesity.PowerShell.psd1
Add powershell model to patch backward compatibility for updating protection job
> Backward compatibility for setting email on the protection job

- docs/cmdlets-reference/register-cohesityprotectionsourcehyperv.md
- src/Cohesity.Powershell/Scripts/ProtectionSource/Register-CohesityProtectionSourceHyperV.ps1
This is to fix the registration fo the HyperV commandlet.
> HyperV Register commandlet fix 

- src/Cohesity.Powershell/Cohesity.PowerShell.Core.psd1
- src/Cohesity.Powershell/Cohesity.PowerShell.psd1
- src/Cohesity.Powershell/Scripts/ProtectionPolicy/New-CohesityProtectionPolicy.ps1
- src/Cohesity.Powershell/Scripts/Vault/Get-CohesityVault.ps1
Added a new cmdlet Get-CohesityVault
> Fix for associating external target for protection policy

- src/Cohesity.Powershell/Cohesity.PowerShell.Core.psd1
- src/Cohesity.Powershell/Cohesity.PowerShell.psd1
- src/Cohesity.Powershell/Scripts/InterfaceGroup/Get-CohesityInterfaceGroup.ps1
- src/Cohesity.Powershell/Scripts/ProtectionSource/Register-CohesityProtectionSourceIsilon.ps1
- src/Cohesity.Powershell/Scripts/Utility/Invoke-RestApi.ps1
- src/Cohesity.Powershell/Scripts/VirtualIP/Get-CohesityVirtualIP.ps1
- src/Cohesity.Powershell/Scripts/VirtualIP/New-CohesityVirtualIP.ps1
- src/Cohesity.Powershell/Scripts/VirtualIP/Remove-CohesityVirtualIP.ps1
- src/Cohesity.Powershell/Scripts/Vlan/New-CohesityVlan.ps1
- src/Cohesity.Powershell/Scripts/Vlan/Remove-CohesityVlan.ps1
- src/Cohesity.Powershell/Scripts/Vlan/Update-CohesityVlan.ps1
- Replaced the csharp cmdlet with script based for Register-
CohesityProtectionSourceIsilon
- Added new cmdlets New-CohesityVirtualIP, Remove-CohesityVirtualIP, Get-
CohesityVirtualIP, Get-CohesityInterfaceGroup, New-CohesityVlan, Update-
CohesityVlan, Remove-CohesityVlan
> Added cmdlets

- src/Cohesity.Powershell/Tools/Generate-CohesityPSCmdletTemplate.ps1
Code generator for Cohesity powershell script cmdlets.
> Template for code generator

- src/Cohesity.Powershell/Cohesity.PowerShell.Core.psd1
- src/Cohesity.Powershell/Cohesity.PowerShell.psd1
- src/Cohesity.Powershell/Scripts/Routes/Get-CohesityRoutes.ps1
- src/Cohesity.Powershell/Scripts/Routes/New-CohesityRoutes.ps1
- src/Cohesity.Powershell/Scripts/Routes/Remove-CohesityRoutes.ps1
New-CohesityRoutes, Get-CohesityRoutes, Remove-CohesityRoutes
Added piping to Remove-CohesityRoutes
Added filter in Get-CohesityRoutes
> Adding cmdlets for routes

- docs/cmdlets-reference/new-cohesityhypervprotectionjob.md
- docs/sidebar.md
- src/Cohesity.Powershell/Scripts/ProtectionJob/New-CohesityHypervProtectionJob.ps1
> Adding start time for hyperv job creation

- src/Cohesity.Powershell/Cohesity.PowerShell.Core.psd1
- src/Cohesity.Powershell/Cohesity.PowerShell.psd1
- src/Cohesity.Powershell/Scripts/QOSPolicy/Get-CohesityQOSPolicy.ps1
- src/Cohesity.Powershell/Scripts/View/Copy-CohesityView.ps1
Replaced the C# based cmdlet with the script based. Now the cmdlet will also support cloning from a inactive view.
> Fix clone view

- src/Cohesity.Powershell/Cmdlets/Cluster/ConnectCohesityCluster.cs
- src/Cohesity.Powershell/Common/RestApiClient.cs
- src/Cohesity.Powershell/Common/UserProfile.cs
- src/Cohesity.Powershell/Common/UserProfileProvider.cs
- src/Cohesity.Powershell/Scripts/Utility/Invoke-RestApi.ps1
Save the credentials in the current session, do not save the Credentials in file.
> Save the credentials in the current session

- src/Cohesity.Powershell/Cmdlets/ProtectionJob/SetCohesityProtectionJob.cs
Protection job can be updated using sources of type KPhysicalFiles. 
Tested with 2 windows servers. Yet to be tested on linux based servers. Need 2 linux servers.
> Fix job physical files

- src/Cohesity.Powershell/Cmdlets/ProtectionSource/GetCohesityProtectionSourceObject.cs
For SQL response, returning only the SQL items associated with the instance name
> SQL query fix

- samples/RestoreSQLDB/README.md
- samples/RestoreSQLDB/restoreDB.ps1
Extending the functionality, accept multiple databases for a particular instance
> Extending the functionality for restore db sample

- docs/cmdlets-reference/get-cohesityprotectionsourcesummary.md
- src/Cohesity.Powershell/Cohesity.PowerShell.Core.psd1
- src/Cohesity.Powershell/Cohesity.PowerShell.psd1
- src/Cohesity.Powershell/Scripts/Utility/Get-CohesityProtectionSourceSummary.ps1
Returning the dashboard object with the query, "/irisservices/api/v1/public/dashboard?clusterId=121212"
> Added cmdlet to get summary of protection sources

- samples/RestoreSQLDB/README.md
- samples/RestoreSQLDB/restoreDB.ps1
updated the readme file with example
> Amendment as per customer request for the SQL db restore sample

- docs/cmdlets-reference/new-cohesityvirtualip.md
- docs/sidebar.md
- src/Cohesity.Powershell/Scripts/VirtualIP/New-CohesityVirtualIP.ps1
> Fixed FQDN for virtual IPs

- docs/cmdlets-reference/set-cohesityprotectionsource.md
- docs/sidebar.md
- src/Cohesity.Powershell/Cohesity.PowerShell.Core.psd1
- src/Cohesity.Powershell/Cohesity.PowerShell.psd1
- src/Cohesity.Powershell/Scripts/ProtectionSource/Set-CohesityProtectionSource.ps1
The cmdlet shall work for various protection sources.
> Update protection source

- docs/cmdlets-reference/restore-cohesitymssqlobject.md
- src/Cohesity.Powershell/Cmdlets/Recovery/RestoreCohesityMSSQLObject.cs
There are 2 fixes,
- The documentation for restore SQL while restoring to and alternate target.
- Added an option "TargetSecondaryDataFilesDirectoryList"  to restore in a secondary folder.
> Enhancement Restore SQL

- Samples/ProtectionJobRun/StartJobWithCopyRunTargets.ps1
- src/Cohesity.Powershell/Cmdlets/Recovery/RestoreCohesityMSSQLObject.cs
Restore-CohesityMSSQLObject -TaskName "sql-restore-task-point-in-time6" -SourceId 1887 -HostSourceId 1863 -JobId 71802 -JobRunId 72142 -StartTime 1602668162043983 -NewDatabaseName 'DBTest6' -TargetDataFilesDirectory 'C:\dbfiles' -TargetLogFilesDirectory 'C:\logfiles' -RestoreTimeSecs 1602666600
> Fixed RestoreTimeSecs for sql logs restore,

- src/Cohesity.Powershell/Cohesity.Powershell.csproj
- src/Cohesity.Powershell/Common/CmdletConfiguration.cs
- src/Cohesity.Powershell/Common/CohesityLog.cs
- src/Cohesity.Powershell/Common/RestApiClient.cs
- src/Cohesity.Powershell/Common/RestApiOperations.cs
- src/Cohesity.Powershell/Scripts/Utility/CSLog.ps1
- src/Cohesity.Powershell/Scripts/Utility/Invoke-RestApi.ps1
Uniform logging through script and C#.
> Release 169 0

- docs/cmdlets-reference/new-cohesitygenericprotectionjob.md
- docs/cmdlets-reference/register-cohesityprotectionsourceaws.md
- docs/sidebar.md
- src/Cohesity.Powershell.Models/Alert.cs
- src/Cohesity.Powershell.Models/BackupRun.cs
- src/Cohesity.Powershell/Cohesity.PowerShell.Core.psd1
- src/Cohesity.Powershell/Cohesity.PowerShell.psd1
- src/Cohesity.Powershell/Scripts/ProtectionJob/New-CohesityGenericProtectionJob.ps1
- src/Cohesity.Powershell/Scripts/ProtectionSource/Register-CohesityProtectionSourceAWS.ps1
- src/Cohesity.Powershell/Scripts/Restore/Restore-CohesityRemoteMSSQLObject.ps1
Added cmdlet to register AWS protection source and generic protection job cmdlet.
> Release 171 0

- docs/cmdlets-reference/register-cohesityprotectionsourceaws.md
- src/Cohesity.Powershell/Scripts/ProtectionSource/Register-CohesityProtectionSourceAWS.ps1
AWS protection source registration
> Release 175 0

- src/Cohesity.Powershell/Scripts/Restore/Restore-CohesityRemoteMSSQLObject.ps1
DBRestoreOverwritePolicy option included to overwrite the existing database if present
> DBRestoreOverwritePolicy option included

- src/Cohesity.Powershell/Cohesity.PowerShell.Core.psd1
- src/Cohesity.Powershell/Cohesity.PowerShell.psd1
v1.7.8 minor release
Restore-CohesityFileV2 cmdlet added newly 
Get-CohesityAgentStatus cmdlet added newly
> v1.7.8 release

- src/Cohesity.Powershell/Scripts/Restore/Restore-CohesityVMwareVM.ps1
Added overwriteExistingVm to Restore-CohesityVMwareVM as requested in #212
> Add overwriteExistingVm flag for VMware VM restore

- samples/ProtectionJob/CreateMSSQLJob.ps1
- src/Cohesity.Powershell.Models/AdGuidPair.cs
- src/Cohesity.Powershell.Models/RpoSchedule.cs
- src/Cohesity.Powershell.Models/ThrottlingConfiguration.cs
- src/Cohesity.Powershell/Cmdlets/ProtectionJob/NewCohesityProtectionJob.cs
- src/Cohesity.Powershell/Cmdlets/Recovery/FindCohesityFilesForRestore.cs
- src/Cohesity.Powershell/Scripts/Restore/Restore-CohesityVMwareVM.ps1
1. Job creation: Sample code for SQL job creation with environment based parameters.
2. Restore files to support more than 100 files(default), option to support pagination, page size and cookie.
3. Restore existing VM during VM recovery.
4. Fixed Get-CohesityMSSQLObject: Could not convert string to integer: kNoThrottling.
https://github.com/cohesity/cohesity-powershell-module/issues/207
> Minor Powershell Code Fixes

- src/Cohesity.Powershell/Cmdlets/Cluster/ConnectCohesityCluster.cs
- src/Cohesity.Powershell/Cohesity.PowerShell.Core.psd1
- src/Cohesity.Powershell/Cohesity.PowerShell.psd1
- src/Cohesity.Powershell/Scripts/Utility/Invoke-RestApi.ps1
Made SSL protocol to use TLS1.2 while connecting to cohesity cluster through web request.
> SSL Protocol Fix

- docs/cmdlets-reference/find-cohesityremotefilesnapshot.md
- docs/cmdlets-reference/restore-cohesityremotefile.md
- docs/cmdlets-reference/restore-cohesityremotefilev2.md
- docs/sidebar.md
- src/Cohesity.Powershell.Models/BackupRun.cs
- src/Cohesity.Powershell/Cohesity.PowerShell.Core.psd1
- src/Cohesity.Powershell/Cohesity.PowerShell.psd1
- src/Cohesity.Powershell/Cohesity.format.ps1xml
- src/Cohesity.Powershell/Scripts/Restore/Find-CohesityFileSnapshot.ps1
- src/Cohesity.Powershell/Scripts/Restore/Find-CohesityRemoteFileSnapshot.ps1
- src/Cohesity.Powershell/Scripts/Restore/Restore-CohesityRemoteFileV2.ps1
1. Added cmdlet for finding remote file snapshot
2. Added cmdlet to restore remote file/folder
3. Fixed issue in enum value in backupRun model. Added additional enum 'kWarning'
> Release 1.9.5 changes:

- src/Cohesity.Powershell/Cmdlets/Cluster/ConnectCohesityCluster.cs
- src/Cohesity.Powershell/Cohesity.PowerShell.Core.psd1
- src/Cohesity.Powershell/Cohesity.PowerShell.psd1
> Made Changes on StatusCode Check
